# -*- coding: utf-8 -*-
"""DS miniproject.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1s2uwq7TgQUs7ip2YZKG42FajDcPE6qLm
"""

#import libraries
import pandas as pd
import numpy as np
import seaborn as sns

#read dataset
df=pd.read_csv("/content/covid_vaccine_statewise.csv")

df

df.head(5)

df.shape        #rows,columns

df.count()         #gives count of features of dataset

df.duplicated().values.any()          #checks duplicate values

df.isna().values.any()               #checks null values

df.describe()                     #gives summary statstics

df.info()

states=np.unique(df['State'])
print(states)

jk=df[df['State']=='Jammu and Kashmir']        #for a particular state
jk['First Dose Administered'].sum()

#Number of persons state wise vaccinated for first dose in India
vaccine_df_by_State = df.groupby("State")[['First Dose Administered']].sum().reset_index()
vaccine_df_by_State

#Number of persons state wise vaccinated for second dose in India
vaccine_df_by_State = df.groupby("State")[['Second Dose Administered']] .sum().reset_index()
vaccine_df_by_State

#Number of Males vaccinated 
plt.figure(figsize=(10,6))
plt.fill_between(df.index,df['Male(Individuals Vaccinated)'])
plt.title("Number of Male(Individuals Vaccinated)")
plt.ylabel("Male(Individuals Vaccinated)") 
plt.xlabel(" Total Doses Administered ") 
# sns.barplot(x=df.index, y=df['Male(Individuals Vaccinated)'] )

#Number of Females vaccinated 
plt.figure(figsize=(10,6))
plt.fill_between(df.index,df['Female(Individuals Vaccinated)'])
plt.title("Number of Female(Individuals Vaccinated)")
plt.ylabel("Female(Individuals Vaccinated)") 
plt.xlabel(" Total Doses Administered ") 
# sns.barplot(x=df.index, y=df['Male(Individuals Vaccinated)'] )

#max no of males vaccinated
males=df['Male(Individuals Vaccinated)']
males.max()

#max no of females vaccinated
females=df['Female(Individuals Vaccinated)']
females.max()